const SHOW = "SHOW";
const MANAGER_CONT_SHOW = "MANAGER_CONT_SHOW";
const NAVBAR_SHOW = "NAVBAR_SHOW";
const REGISTRATION_USER = "REGISTRATION_USER";
const EMPLOYEE_DATA = "EMPLOYEE_DATA";
const GET_PORFESSION = "GET_PORFESSION";
const GET_TASKS = "GET_TASKS";
const GET_STUFF = "GET_STUFF";
const GET_ORG = "GET_ORG";
const GET_ARCHIVE = "GET_ARCHIVE";
const SEARCH = "SEARCH";
const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";
const GET_MANAGER = "GET_MANAGER";
const GET_STUFF_LIMIT = "GET_STUFF_LIMIT";
const GET_ORG_LIMIT = "GET_ORG_LIMIT";
const GET_REPEATED_TASKS = "GET_REPEATED_TASKS";
const DELETE_SEARCH = "DELETE_SEARCH";
const LOADING = "LOADING";
const ACTIVEPAGE = "ACTIVEPAGE";
const LOADING_ORG = "LOADING_ORG";
const ACTIVEPAGE_ORG = "ACTIVEPAGE_ORG";
const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";
const GET_SEE_NOTIFICATION = "GET_SEE_NOTIFICATION";
const GET_NOTIFICATION = "GET_NOTIFICATION";
const TASK_DATA = "TASK_DATA";
const DELETE_TASK_DATA = "DELETE_TASK_DATA";
const CHANGE_STATUS = "CHANGE_STATUS";
const TYPEACTIVITY = "TYPEACTIVITY";
const TAXATION_SYSTEM = "TAXATION_SYSTEM";
const GET_CARD = "GET_CARD";
const GET_ORG_LIST = "GET_ORG_LIST";
const GET_COMPANY_FILE = "GET_COMPANY_FILE";
const COMPANY_SERVICE = "COMPANY_SERVICE";
const LAODER_ORG = "LAODER_ORG";
const LOADER_STUFF = "LOADER_STUFF";
const LOADER_FILTER = "LOADER_FILTER";
const LOADER_COMPANY_FILE = "LOADER_COMPANY_FILE";
const GET_TASKS_TEMPLATE = "GET_TASKS_TEMPLATE";
const GET_TASK_SMS = "GET_TASK_SMS";
const NEW_TASK_SMS = "NEW_TASK_SMS";
const CLEAN_TASKSMS = "CLEAN_TASKSMS";
const SET_DAY_REPORTS = "SET_DAY_REPORTS";
export {
    SHOW, MANAGER_CONT_SHOW, NAVBAR_SHOW, REGISTRATION_USER, EMPLOYEE_DATA, GET_PORFESSION, GET_TASKS, GET_STUFF,
    GET_ORG, GET_ARCHIVE, SEARCH, GET_EMPLOYEE_DATA, GET_MANAGER, GET_ORG_LIMIT, GET_STUFF_LIMIT, GET_REPEATED_TASKS,
    DELETE_SEARCH, LOADING, ACTIVEPAGE, LOADING_ORG, ACTIVEPAGE_ORG, DELETE_EMPLOYEE_DATA, GET_SEE_NOTIFICATION,
    GET_NOTIFICATION, TASK_DATA, DELETE_TASK_DATA, CHANGE_STATUS, TYPEACTIVITY, TAXATION_SYSTEM, GET_CARD, GET_ORG_LIST,
    GET_COMPANY_FILE, COMPANY_SERVICE, LAODER_ORG, LOADER_STUFF, LOADER_FILTER, LOADER_COMPANY_FILE, GET_TASKS_TEMPLATE,
    GET_TASK_SMS, NEW_TASK_SMS, CLEAN_TASKSMS, SET_DAY_REPORTS
}